# Vagrant configuration for an Ubuntu VM
# Author: Andrew Jarombek
# Date: 10/16/2023

Vagrant.configure("2") do |config|
    # Use the "generic/ubuntu2204" base box as the starting point for the VM
    config.vm.box = "generic/ubuntu2204"

    # Sync a folder relative to the location of the Vagrantfile
    config.vm.synced_folder "src", "/app"

    # Create a private network for the VM with DHCP for automatic IP assignment
    config.vm.network "private_network", type: "dhcp"

    # Specify VM settings for the VirtualBox provider
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true

        # Set the amount of memory allocated to the VM to 2048 MB (2 GB)
        vb.memory = "2048"
        vb.cpus = "2"
    end
end
